# Generated by Django 4.1.5 on 2023-02-17 16:54

from django.db import migrations, models
import users.validator


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customusers_group_remove_customusers_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusers',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 100 characters or fewer. Letters, digits and - only.', max_length=100, unique=True, validators=[users.validator.UnicodeUsernameValidatorNew()], verbose_name='username'),
        ),
    ]
