# Generated by Django 4.1.5 on 2023-02-20 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_customusers_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusers',
            name='is_confirmed',
            field=models.BooleanField(default=False, verbose_name='Подтвержден Email'),
        ),
    ]
