# Generated by Django 4.1.5 on 2023-01-30 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(db_index=True, max_length=200, verbose_name='Город')),
                ('slug', models.SlugField(max_length=80, unique=True, verbose_name='url slug')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='MainContentReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Дата обнавления')),
                ('review_author', models.CharField(default='Анонимно', max_length=200, verbose_name='Автор')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('review_content', models.TextField(verbose_name='Отзыв')),
            ],
            options={
                'verbose_name': 'Отзыв услуг',
                'verbose_name_plural': 'Отзывы услуг',
            },
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization_name', models.CharField(db_index=True, max_length=100, verbose_name='Специализация')),
                ('slug', models.SlugField(max_length=80, unique=True, verbose_name='url slug')),
            ],
            options={
                'verbose_name': 'Специализация',
                'verbose_name_plural': 'Специализации',
            },
        ),
        migrations.CreateModel(
            name='MainUserContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_type_name', models.CharField(db_index=True, max_length=255, verbose_name='Вид работы')),
                ('title', models.CharField(max_length=200, verbose_name='title страницы')),
                ('h1', models.CharField(max_length=100, verbose_name='Тэг H1')),
                ('slug', models.SlugField(max_length=80, unique=True, verbose_name='url slug')),
                ('main_content', models.TextField(verbose_name='Основной сео контент')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main_user_content.city', verbose_name='Город')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main_user_content.specialization', verbose_name='Специализация')),
            ],
            options={
                'verbose_name': 'Основной пользовательский контент',
                'verbose_name_plural': 'Основной пользовательский контент',
            },
        ),
        migrations.CreateModel(
            name='MainContentReviewAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Дата обнавления')),
                ('review_author', models.CharField(default='Анонимно', max_length=200, verbose_name='Автор')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('answer_content', models.TextField(verbose_name='Ответ')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_user_content.maincontentreview', verbose_name='Отзыв')),
            ],
            options={
                'verbose_name': 'Ответ на отзывы усл.',
                'verbose_name_plural': 'Ответы на отзывы усл.',
            },
        ),
        migrations.AddField(
            model_name='maincontentreview',
            name='work_type_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main_user_content.mainusercontent', verbose_name='Вид работы'),
        ),
    ]
