# Generated by Django 4.1.5 on 2023-01-30 05:06

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_user_content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainusercontent',
            name='main_content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Основной сео контент'),
        ),
    ]
