# Generated by Django 4.1.5 on 2023-02-01 08:20

from django.db import migrations, models
import main_user_content.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_user_content', '0003_telephonenumber_alter_mainusercontent_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telephonenumber',
            name='telephone_number',
            field=models.CharField(max_length=11, validators=[main_user_content.models.telephone_validator], verbose_name='Номер телефона начиная с 8 без пробелов и скобок, только цифры'),
        ),
    ]
