# Generated by Django 4.1.5 on 2023-02-02 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_user_content', '0004_alter_telephonenumber_telephone_number'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mainusercontent',
            unique_together={('work_type_name', 'city')},
        ),
        migrations.CreateModel(
            name='OneMainCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main_user_content.city', verbose_name='Основной Город, услуги по которому отображаются в меню по умолчанию (при не выбранном городе).')),
            ],
            options={
                'verbose_name': 'Город по умолчанию',
                'verbose_name_plural': 'Города по умолчанию',
            },
        ),
    ]
