# Generated by Django 4.1.5 on 2023-02-02 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_user_content', '0005_alter_mainusercontent_unique_together_onemaincity'),
    ]

    operations = [
        migrations.AddField(
            model_name='onemaincity',
            name='slug',
            field=models.SlugField(default=3, max_length=80, verbose_name='Технический slug'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='onemaincity',
            name='main_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main_user_content.city', verbose_name='Основной 1 Город, услуги по которому отображаются в меню по умолчанию (при не выбранном городе).'),
        ),
    ]
