# Generated by Django 4.1.5 on 2023-02-02 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_user_content', '0009_alter_onemaincity_city_id_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onemaincity',
            name='city_id_field',
            field=models.IntegerField(default=1, verbose_name='ID Не менять'),
        ),
    ]
