# Generated by Django 4.1.5 on 2023-02-03 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_user_content', '0010_alter_onemaincity_city_id_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='услуги по городу отображаются в меню по умолчанию'),
        ),
        migrations.DeleteModel(
            name='OneMainCity',
        ),
    ]
