# Generated by Django 4.1.5 on 2023-02-03 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_user_content', '0011_city_is_default_delete_onemaincity'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainusercontent',
            name='preview_img',
            field=models.ImageField(null=True, upload_to='type-preview/%Y/%m/%d/', verbose_name='Картинка превью в списке услуг'),
        ),
        migrations.AlterField(
            model_name='city',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='услуги по выбранному городу отображаются в меню по умолчанию (1шт.)'),
        ),
    ]
