# Generated by Django 4.1.5 on 2023-02-03 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_user_content', '0012_mainusercontent_preview_img_alter_city_is_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maincontentreview',
            name='work_type_name',
        ),
        migrations.AddField(
            model_name='maincontentreview',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='main_user_content.city', verbose_name='Город'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maincontentreview',
            name='specialization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='main_user_content.specialization', verbose_name='Специализация'),
            preserve_default=False,
        ),
    ]
