# Generated by Django 4.1.5 on 2023-02-07 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_user_content', '0013_remove_maincontentreview_work_type_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maincontentreview',
            name='work_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='main_user_content.mainusercontent', verbose_name='Вид работ'),
            preserve_default=False,
        ),
    ]
