# Generated by Django 4.1.5 on 2023-02-07 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_user_content', '0014_maincontentreview_work_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_type', models.CharField(db_index=True, max_length=255, verbose_name='Вид работы')),
                ('slug', models.SlugField(max_length=80, verbose_name='url slug')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='mainusercontent',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='mainusercontent',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='mainusercontent',
            name='work_type_name',
        ),
        migrations.AddField(
            model_name='mainusercontent',
            name='work_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='main_user_content.worktype', verbose_name='Вид работы'),
            preserve_default=False,
        ),
    ]
