# Generated by Django 4.1.5 on 2023-02-07 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_user_content', '0016_alter_worktype_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maincontentreview',
            name='work_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main_user_content.worktype', verbose_name='Вид работ'),
        ),
    ]
