# Generated by Django 4.1.5 on 2023-02-14 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_user_content', '0018_rename_work_type_worktype_work_type_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maincontentreview',
            name='work_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main_user_content.worktype', verbose_name='Вид работ'),
        ),
    ]
