# Generated by Django 4.1.5 on 2023-02-26 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_user_content', '0020_alter_maincontentreview_review_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maincontentreviewanswer',
            name='review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_user_content.maincontentreview', verbose_name='Отзыв'),
        ),
    ]
